### ISSUE TITLE
[Calendar] delete activity icon is cut

### ISSUE THREAD

**Issue by sebastiendavid** [PierreLeresteux/timesheet-nodejs-mongo#2]
How to reproduce: mouse over claquoss, delete icon is displayed and cut on the top

Browser: Chrome linux

**Comment by PierreLeresteux** [comment]
Claquos and icon have not the same size ...

**Comment by sebastiendavid** [comment]
idea: remplacer le claquoss par du simple texte...

**Comment by sebastiendavid** [comment]
nop... claquoss: 16x15, delete: 16x16

**Comment by sebastiendavid** [comment]
cf. google groups

**Comment by PierreLeresteux** [comment]
OK
![](http://i.imgur.com/RJwKB.jpg)
